config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :appointments
  resources :beds
  resources :patients
  resources :doctors

  namespace :admin do
    resources :doctors
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @doctors = Doctor.all
        doctor_count = @doctors.count
        @doctor_count = doctor_count

        @patients = Patient.all
        patient_count = @patients.count
        @patient_count = patient_count

        @appointments = Appointment.all
        appointment_count = @appointments.count
        @appointment_count = appointment_count

        @beds = Bed.all
        bed_count = @beds.count
        @bed_count = bed_count

    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<main class="main">
  <h1 class="wrapper display hospital mt-5"><strong>Hospital Management Information System</strong></h1>
    <section class="card-area">

      <!-- Card: doctors -->
      <section class="card-section">
        <div class="card">
          <div class="flip-card">
            <div class="flip-card__container">
              <div class="card-front">
                <div class="card-front__tp card-front__tp--doctors">
                  <h2 class="card-front__heading">Available Doctors</h2>
                </div>

                <div class="card-front__bt">
                  <p class="card-front__text-view card-front__text-view--doctors">
                    View me
                  </p>
                </div>
              </div>
              <div class="card-back"></div>
            </div>
          </div>

          <div class="inside-page">
            <div class="inside-page__container">
              <h3 class="inside-page__heading inside-page__heading--doctors">
                <%= @doctor_count %>
              </h3>
              <a href="#" class=""></a>
                <%= link_to "View Doctors", doctors_path, class: 'inside-page__btn inside-page__btn--doctors' %>
            </div>
          </div>
        </div>
      </section>

      <!-- Card: Patients -->
      <section class="card-section">
        <div class="card">
          <div class="flip-card">
            <div class="flip-card__container">
              <div class="card-front">
                <div class="card-front__tp card-front__tp--patients">
                  <h2 class="card-front__heading">Patients</h2>
                </div>
                <div class="card-front__bt">
                  <p class="card-front__text-view card-front__text-view--patients">
                    View me
                  </p>
                </div>
              </div>

              <div class="card-back"></div></div>
            </div>

            <div class="inside-page">
              <div class="inside-page__container">
                <h3 class="inside-page__heading inside-page__heading--patients">
                  <%= @patient_count %> 
                </h3>
                  <%= link_to "View Patients", patients_path, class: 'inside-page__btn inside-page__btn--patients'%>
              </div>
            </div>
          </div>
        </section>

        <!-- Card: Appointments -->
        <section class="card-section">
          <div class="card">
            <div class="flip-card">
              <div class="flip-card__container">
                <div class="card-front">
                  <div class="card-front__tp card-front__tp--appointments">
                    <h2 class="card-front__heading">Appointments</h2>
                  </div>
                  <div class="card-front__bt">
                    <p class="card-front__text-view card-front__text-view--appointments">
                      View me
                    </p>
                  </div>
                </div>
              <div class="card-back"></div>
            </div>
          </div>

          <div class="inside-page">
            <div class="inside-page__container">
              <h3 class="inside-page__heading inside-page__heading--appointments">
                <%= @appointment_count %>
              </h3>
                <%= link_to "Appointment", appointments_path, class: "inside-page__btn inside-page__btn--appointments"%>
            </div>
          </div>
        </div>
      </section>

      <!-- Card: Beds -->
      <section class="card-section">
        <div class="card">
          <div class="flip-card">
            <div class="flip-card__container">
              <div class="card-front">
                <div class="card-front__tp card-front__tp--beds">
                  <h2 class="card-front__heading">Reserved Beds</h2>
                </div>

                <div class="card-front__bt">
                  <p class="card-front__text-view card-front__text-view--beds">
                    View me
                  </p>
                </div>
              </div>
              <div class="card-back"></div>
            </div>
          </div>

          <div class="inside-page">
            <div class="inside-page__container">
              <h3 class="inside-page__heading inside-page__heading--beds">
                <%= @bed_count %>
              </h3>
                <%= link_to "View Beds", beds_path, class: 'inside-page__btn inside-page__btn--beds'%>
            </div>
          </div>
        </div>
      </section>
    </section>
  </main>