config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :appointments
  resources :beds
  resources :patients
  resources :doctors

  namespace :admin do
    resources :doctors
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
    # has_one :bed
    has_one_attached :profile_image
    has_many_attached :documents
    # has_one :Appointment
    # belongs_to :doctor

    validates :name, presence: true
    validates :email, presence: true
    validates :address, presence: true
    validates :disease, presence: true
    validates :dof_enterance, presence: true
    validates :phone, numericality: { only_numeric: true }
    validates :email, 
    format: { with: /\A(.+)@(.+)\z/, message: "invalid"  }, 
    uniqueness: { case_sensitive: false }
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
     params. require(:patient).permit(:name, :email, :disease, :dof_enterance, :dof_exit, :address, :phone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div class="wrapper">
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> Prohibited this patient from being saved:</h2>
      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="bg-success p-5 row text-light shadow-lg">
  <div class="col-md-6 col-sm-12">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name , class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control'%>
    </div>
  
    <div class="form-group">
      <%= form.label :disease%>
      <%= form.text_field :disease, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :phone %>
      <%= form.text_field :phone, class: 'form-control'%>
    </div>
  </div>
  <div class="col-md-6 col-sm-12">
    <div class="form-group">
      <%= form.label :"Date Of Enterance"%>
      <%= form.date_field :dof_enterance, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :"Date Of Exit"%>
      <%= form.date_field :dof_exit, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <div>
      <%=link_to form.submit class: 'btn btn-md btn-warning mt-4 col-12'%>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">

  <td><%= patient.name %></td>
  <td><%= patient.email %></td>

</div>

app/views/patients/edit.html.erb
<div class="mt-5">
  <%= render "form", patient: @patient %>
</div>
<div class="wrapper mt-4 mb-4">
  <%= link_to "Details", @patient, class: 'btn btn-small btn-primary m-2'  %>
  <%= link_to "Back", patients_path, class: "btn btn-danger btn-small m-2"  %>
</div>

app/views/patients/index.html.erb
<p class="badge bg-success"><%= notice %></p>

<h1 class="text-center mt-4 wrapper display hospital"><strong>Patients</strong></h1>

<div id="patients" class="row">
 <table class="table table-hover mt-5 col-6">
  <% @patients.each do |patient| %>
    <tr>
    <td><%= render patient %></td>

    <td><%= link_to "Update", edit_patient_path(patient), class: 'btn btn-warning' %></td>

    <td><%= link_to "Details", patient, class: 'btn btn-primary' %></td>

    <td><%= button_to "Delete", patient, method: :delete, class: 'btn btn-danger' %></td>
    </tr>
    
  <% end %>
  </table>
</div>
<div class="wrapper"><%= link_to "Register", new_patient_path, class: "btn btn-secondary mb-3" %></div>

app/views/patients/new.html.erb
<div class="mt-5">
  <%= render "form", patient: @patient %>
</div>

<div class="wrapper mt-4">
  <%= link_to "Cancel", patients_path, class: 'btn btn-small btn-danger mb-3' %>
</div>

app/views/patients/show.html.erb
<style>
.wrapper {
  display: flex;
  flex-direction: row;
  justify-content: center;
}

.patient {
  background: linear-gradient(to bottom, #ebef06, #ffb338);
  padding: 30px;
  margin-top: 40px;
  border: 1px white solid;
  border-radius: 0 50px 0 50px;
  box-shadow: 0 10px 15px #b1b1b1;
}

.patient:hover {
  color: white;
  box-shadow: 0 20px 30px 0#989898;
}

.hospital {
  background: linear-gradient(
    to bottom,
    #7afd6e,
    #0b4527
   );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  animation-duration: 3s;
  animation-name: slidein;
  animation-iteration-count: 1;
  animation-direction: alternate;
}

@keyframes slidein {
  from {
    margin-top: -100%;
  }
  to {
    margin-top: 0%;
  }
}
</style>
<p class="badge bg-success"><%= notice %></p>

<div class="row">
  <div id="patients" class=" wrapper">
  <div class="patient col-6 flex justify-content-center">
        <h2 class="display-1 hospital pb-2 text-center">
          <strong><%= @patient.name %></strong>
        </h2>
    
        <p class="text-center">
          <strong>Email:
          <%= @patient.email %></strong>
        </p>
        <p class="text-center">
          <strong>Disease:
          <%= @patient.disease %></strong>
        </p>
        <p class="text-center">
          <strong>Date of Enterance:
          <%= @patient.dof_enterance %></strong>
        </p>
        <p class="text-center">
          <strong>Date Of Exit:
          <%= @patient.dof_exit %></strong>
        </p>
        <p class="text-center">
          <strong>Address:
          <%= @patient.address %></strong>
        </p>
        <p class="text-center">
          <strong>Phone:
          <%= @patient.phone %></strong>
        </p>
    </div>
  </div>
</div>
<div class="wrapper">
  <%= link_to "Edit", edit_patient_path(@patient), class: 'btn btn-small btn-primary m-4' %>
  <%= link_to "Back", patients_path, class: 'btn btn-small btn-warning m-4' %>
  <%= button_to "Delete", @patient, method: :delete, class: 'btn btn-small btn-danger m-4' %>

</div>