config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :appointments
  resources :beds
  resources :patients
  resources :doctors

  namespace :admin do
    resources :doctors
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :patients
    has_many :appointments
    has_one_attached :profile_image

    validates :name, presence: true
    validates :profile_image, presence: true
    validates :address, presence: true
    validates :email, presence: true
    validates :speciality, presence: true
    validates :phone, numericality: { only_numeric: true }
    validates :bio, length: { minimum: 200, maximum: 1000 }
    validates :email, 
    format: { with: /\A(.+)@(.+)\z/, message: "Email invalid"  }, 
    uniqueness: { case_sensitive: false }  
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[show edit update destroy]

  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :email, :bio, :speciality, :address, :phone, :profile_image)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <td><%= doctor.name %></td>
  <td><%= doctor.email %></td>
</div>

app/views/doctors/_form.html.erb
<div class="wrapper">
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="bg-success p-5 row text-light shadow-lg">
  <div class="col-md-6 col-sm-12">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email, class: 'form-control' %>
      </div>

    <div class="form-group">
      <%= form.label :speciality %>
      <%= form.text_field :speciality, class: 'form-control' %>
    </div>

      <div class="form-group">
        <%= form.label :bio %>
        <%= form.text_area :bio, class: 'col-12 h-7' %>
      </div>
    </div>
  <div class="col-md-6 col-sm-12">

    <div class="form-group">
        <%= form.label :profile_image %>
        <%= form.file_field :profile_image, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: 'form-control' %>
    </div>

    <div class="">
      <%=link_to form.submit class: 'btn btn-md btn-warning mt-4 col-12'%>
    </div>
  </div>
<% end %>
</div>

app/views/doctors/edit.html.erb
<div class="mt-5">
  <%= render "form", doctor: @doctor %>
</div>
<div class="wrapper mt-5">
  <%= link_to "Details", @doctor, class: 'btn btn-small btn-primary m-2' %>
  <%= link_to "Back to doctors", doctors_path, class: "btn btn-danger btn-small m-2" %>
</div>

app/views/doctors/index.html.erb
<p class="badge bg-success"><%= notice %></p>

<h1 class="text-center mt-4 text-success hospital"><strong>Doctors</strong></h1>

<div id="doctors">
 <table class="table table-hover mt-5 col-6">
   <% @doctors.each do |doctor| %>
    <tr>
    <td><%= render doctor %></td>

    <td><%= link_to "Update", edit_doctor_path(doctor), class: 'btn btn-warning' %></td>

    <td><%= link_to "Details", doctor, class: 'btn btn-primary' %></td>

    <td><%= button_to "Delete", doctor, method: :delete, class: 'btn btn-danger' %></td>

  <% end %>
  </table>
</div>
<div class="wrapper"><%= link_to "Register", new_doctor_path, class: "btn btn-secondary mb-3" %></div>

app/views/doctors/new.html.erb
<div class="mt-5">
  <%= render "form", doctor: @doctor %>
</div>
<div class='wrapper mt-4'>
  <%= link_to "Cancel", doctors_path, class: 'btn btn-small btn-danger mb-3' %>
</div>

app/views/doctors/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="doctors">
 <div class="row">
  <div class="col-7 p-5">
    <h2 class="display-1 hospital">
      <strong><%= @doctor.name %></strong>
    </h2>

    <p class="bg-success rounded text-light p-5 shadow-lg">
      <strong>Bio:</strong>
      <%= @doctor.bio %>
    </p>

    <p class="badge bg-primary p-2">
      <strong>Speciality:</strong>
      <%= @doctor.speciality %>
    </p>

    <p class="badge bg-warning p-2">
      <strong>Address:</strong>
      <%= @doctor.address %>
    </p>

    <p class="badge bg-danger p-2">
      <strong>Email:</strong>
      <%= @doctor.email %>
    </p>

    <p class="badge bg-secondary p-2">
      <strong>Phone:</strong>
      <%= @doctor.phone %>
    </p>
      </div>
  <div class="col-5 flex justify-content-center p-5">
  <div>
  <% if @doctor.profile_image.attached? %>
    <%= image_tag @doctor.profile_image, style: 'width:400px; height:400px', class:'rounded-circle shadow-lg' %>
  <% end %>
  </div>
  <div class="wrapper mt-2">
    <%= link_to "Edit", edit_doctor_path(@doctor), class: 'btn btn-small btn-primary m-2' %>
  <%= link_to "Back", doctors_path,  class: 'btn btn-small btn-warning m-2' %>
  <%= button_to "Delete", @doctor, method: :delete, class: 'btn btn-small btn-danger m-2' %>
  </div>
  </div>
  </div>
</div>