config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  resources :appointments
  resources :beds
  resources :patients
  resources :doctors

  namespace :admin do
    resources :doctors
  end
end

app/models/bed.rb
class Bed < ApplicationRecord
    # belongs_to :patient

    validates :p_name, presence: true
    validates :number, presence: true 
    validates :number, numericality: { only_numeric: true }   
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
  before_action :set_bed, only: %i[ show edit update destroy ]

  # GET /beds or /beds.json
  def index
    @beds = Bed.all
  end

  # GET /beds/1 or /beds/1.json
  def show
    @beds = Bed.all
  end

  # GET /beds/new
  def new
    @bed = Bed.new
  end

  # GET /beds/1/edit
  def edit
  end

  # POST /beds or /beds.json
  def create
    @bed = Bed.new(bed_params)

    respond_to do |format|
      if @bed.save
        format.html { redirect_to bed_url(@bed), notice: "Bed was successfully created." }
        format.json { render :show, status: :created, location: @bed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beds/1 or /beds/1.json
  def update
    respond_to do |format|
      if @bed.update(bed_params)
        format.html { redirect_to bed_url(@bed), notice: "Bed was successfully updated." }
        format.json { render :show, status: :ok, location: @bed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bed.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /beds/1 or /beds/1.json
def destroy
  @bed.destroy
  respond_to do |format|
    format.html { redirect_to beds_url, notice: "Bed was successfully destroyed." }
    format.json { head :no_content }
  end
end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_bed
    @bed = Bed.find(params[:id])
  end

# Only allow a list of trusted parameters through.
  def bed_params
    params.require(:bed).permit(:p_name, :number, :is_reseved)
  end
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/views/beds/_bed.html.erb
<div id="<%= dom_id bed %>">
  <tr>
    <td>
      <%= bed.p_name%>
    </td>
    <td>
      <%= bed.number %>
    </td>
    <td>
      Reseved
    </td>
</div>

app/views/beds/_form.html.erb
<div class="wrapper">
<%= form_with(model: bed) do |form| %>
  <% if bed.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bed.errors.count, "error") %> prohibited this bed from being saved:</h2>

      <ul>
        <% bed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="bg-success p-5 row text-light shadow-lg">
    <div>
      <%= form.label :"Patient" %>
      <%= form.text_field :p_name, class: 'form-control'%>
    </div>
    <div>
      <%= form.label :"Number" %>
      <%= form.text_field :number, class: 'form-control' %>
    </div>

    <div>
      <%= form.label :"Reserve" %>
      <%= form.text_field :is_reserved, class: 'form-control' %>
    </div>

    <div>
      <%=link_to form.submit class: 'btn btn-md btn-warning mt-4 col-12'%>
    </div>
  <% end %>
  </div>
</div>

app/views/beds/edit.html.erb
<div class="mt-5">
  <%= render "form", bed: @bed%>
</div>

<div class="wrapper mt-4 mb-4">
  <%= link_to "Cancel", beds_path, class: 'btn btn-danger mt-4' %>
</div>

app/views/beds/index.html.erb
<strong>Total Beds are 50.</strong>
<div class="wrapper">
<p style="color: green"><%= notice %></p>
<table style="width: 80%;border: 1px solid" class="table table-hover mt-5">
  <tr>
    <th>Patient</th>
    <th>Number</th>
    <th>Is reseved</th>
  </tr>
   <% @beds.each do |bed| %>
       <%= render bed %>
       <td><%= link_to "Update", edit_bed_path(bed), class: 'btn btn-warning' %></td>
       <td><%= button_to "Cancel", bed, method: :delete, class: 'btn btn-danger' %></td>
     </tr>
  <% end %>
 </table>
</div>

<div class="wrapper"><%= link_to "New bed", new_bed_path, class: "btn btn-secondary mb-3" %></div>
</div>

app/views/beds/new.html.erb
<div class="mt-5">
  <%= render "form", bed: @bed %>
</div>

<div class="wrapper mt-4 mb-4">
  <%= link_to "Cancel", beds_path, class: 'btn btn-small btn-danger mt-4' %>
</div>

app/views/beds/show.html.erb
<div class="wrapper">
<p style="color: green"><%= notice %></p>
<table style="width: 80%; border: 1px solid" class="table table-hover mt-5">
  <tr>
    <th>Patient</th>
    <th>Number</th>
    <th>Is reseved</th>
  </tr>
   <% @beds.each do |bed| %>
       <%= render bed %>
       <td><%= link_to "Update", edit_bed_path(bed), class: 'btn btn-warning' %></td>
       <td><%= button_to "Cancel", bed, method: :delete, class: 'btn btn-danger' %></td>
     </tr>
  <% end %>
 </table>
</div>

<div class="wrapper"><%= link_to "New bed", new_bed_path, class: "btn btn-secondary mb-3" %></div>
</div>